pdc-discovery index on solr8 staging
pulibrary/pul_solr pull request #284
Opened 2021-07-14 14:28 UTC by bess

2021-07-14 17:33 UTC, hackartisan requested changes
This looks good. You'll also want to add your new config set in https://github.com/pulibrary/pul_solr/blob/main/config/deploy/solr8-staging.rb#L11

You do have to create the collection manually, but once it's created deploying pul_solr will update the config set and reload the collection to get the changes.

2021-07-14 19:59 UTC, bess commented
@hackartisan I am confused by your comment. Didn't I already add my new config set in this PR? 

![Screen Shot 2021-07-14 at 3 57 55 PM](https://user-images.githubusercontent.com/65608/125684962-f30cd17f-933d-4861-87b5-67edf1c4131a.png)

2021-07-15 03:17 UTC, hackartisan commented
Sorry, I looked too quickly. It is https://github.com/pulibrary/pul_solr/blob/main/config/collections.yml that you will want to add it to.

2021-07-20 14:55 UTC, hackartisan approved these changes

2021-07-20 14:55 UTC, merged